name: Create Release Archive
on:
  push:
    tags:
      - v*.0.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        filename: ${{ github.ref_name }} + '.zip'
        directory: .
        path: .
        type: 'zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
